language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit
